### ISSUE TITLE
JustMock.Unity NuGet package fails to install when there is CommonServiceLocator 1.3 on the machine

### ISSUE THREAD

**Issue by Mike4o** [tailsu/Telerik.JustMock.Unity#1]
We are trying to install the JustMock.Unity package from NuGet and fails with the following error:

Attempting to resolve dependency 'JustMock (= 2014.1.1424.1)'.

Attempting to resolve dependency 'CommonServiceLocator (= 1.0)'.

Attempting to resolve dependency 'Unity (= 3.5.1404.0)'.

Installing 'CommonServiceLocator 1.0'.

Successfully installed 'CommonServiceLocator 1.0'.

Installing 'JustMock 2014.1.1424.1'.

Successfully installed 'JustMock 2014.1.1424.1'.

Installing 'JustMock.Unity 1.0.0'.

Successfully installed 'JustMock.Unity 1.0.0'.

Install failed. Rolling back...

Already referencing a newer version of 'CommonServiceLocator'.

We are using the version 1.3 of the CommonServiceLocator package in the production code and we have the latest JustMock installed.

**Comment by tailsu** [comment]
Ah, apparently JustMock.Unity is referencing a bogus version of JustMock. I'll fix the NuGet package.

You can work around this issue by first installing the latest JustMock version from NuGet, and then installing JustMock.Unity

**Comment by tailsu** [comment]
I pushed a new version of the package with the fixed version numbers. Thanks for the bug report!
